"""Static contracts for deterministic dependency and publisher tooling."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCKS = (
    ROOT / "requirements-dev.lock",
    ROOT / "requirements-build.lock",
    ROOT / "requirements-release.lock",
)
REQUIREMENT_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([^ ;\\]+)")


def _canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _lock_entries(path: Path) -> dict[str, str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    starts = [index for index, line in enumerate(lines) if REQUIREMENT_RE.match(line)]
    assert starts, f"{path.name} contains no pinned requirements"

    entries: dict[str, str] = {}
    for position, start in enumerate(starts):
        end = starts[position + 1] if position + 1 < len(starts) else len(lines)
        match = REQUIREMENT_RE.match(lines[start])
        assert match is not None
        block = "\n".join(lines[start:end])
        assert "--hash=sha256:" in block, f"missing SHA-256 hash for {lines[start]}"
        name = _canonical_name(match.group(1))
        assert name not in entries, f"duplicate lock entry: {name}"
        entries[name] = match.group(2)
    return entries


def _direct_pins(path: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = REQUIREMENT_RE.match(line)
        if match:
            pins[_canonical_name(match.group(1))] = match.group(2)
    return pins


def test_all_locks_are_hash_pinned_and_canonically_generated() -> None:
    for lock in LOCKS:
        text = lock.read_text(encoding="utf-8")
        assert text.startswith(
            "# Generated by scripts/regenerate-locks.sh with uv 0.11.29.\n"
        )
        _lock_entries(lock)


def test_release_lock_composes_the_build_lock() -> None:
    build_entries = _lock_entries(ROOT / "requirements-build.lock")
    release_entries = _lock_entries(ROOT / "requirements-release.lock")
    assert _direct_pins(ROOT / "requirements-build.in") == {
        "build": "1.5.0",
        "hatchling": "1.31.0",
    }
    assert _direct_pins(ROOT / "requirements-release.in") == {"twine": "7.0.0"}
    for name, version in build_entries.items():
        assert release_entries.get(name) == version


def test_dev_lock_contains_ci_security_tools_and_mcp_v1() -> None:
    entries = _lock_entries(ROOT / "requirements-dev.lock")
    assert entries["bandit"] == "1.9.4"
    assert entries["pip-audit"] == "2.10.1"
    assert entries["mcp"].split(".", maxsplit=1)[0] == "1"


def test_workflows_use_locks_and_offline_local_builds() -> None:
    paths = (
        ROOT / ".github/workflows/ci.yml",
        ROOT / ".github/workflows/test-api-compat.yml",
        ROOT / ".github/workflows/dependency-audit.yml",
        ROOT / ".github/workflows/publish.yml",
    )
    combined = "\n".join(path.read_text(encoding="utf-8") for path in paths)
    assert "pip install --upgrade pip" not in combined
    assert "--require-hashes -r requirements-dev.lock" in combined
    assert "--require-hashes -r requirements-build.lock" in combined
    assert "--require-hashes -r requirements-release.lock" in combined
    assert 'PIP_NO_INDEX: "1"' in combined
    assert "--no-deps --no-build-isolation -e ." in combined
    assert "python -m build --no-isolation" in combined


def test_publisher_is_exactly_pinned_and_digest_verified() -> None:
    installer = (ROOT / "scripts/install-mcp-publisher.sh").read_text(encoding="utf-8")
    assert 'VERSION="1.8.0"' in installer
    assert (
        'ARCHIVE_SHA256="1370446bbe74d562608e8005a6ccce02d146a661fbd78674e11cc70b9618d6cf"'
        in installer
    )
    assert "releases/download/v${VERSION}/mcp-publisher_linux_amd64.tar.gz" in installer
    assert "sha256sum --check --status" in installer
    assert "--version 2>&1" in installer
    assert "/releases/latest/" not in installer


def test_dependabot_blocks_mcp_semver_major_updates() -> None:
    config = (ROOT / ".github/dependabot.yml").read_text(encoding="utf-8")
    assert 'dependency-name: "mcp"' in config
    assert '"version-update:semver-major"' in config
