#!/usr/bin/env bash
# Regenerate or verify all hash-pinned Python tool locks.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

UV_VERSION="0.11.29"
MODE="${1:---write}"
case "$MODE" in
    --write|--check|--upgrade) ;;
    *)
        echo "usage: $0 [--write|--check|--upgrade]" >&2
        exit 2
        ;;
esac

if ! command -v uv >/dev/null 2>&1; then
    echo "ERROR: uv $UV_VERSION is required." >&2
    exit 1
fi
actual_uv="$(uv --version)"
case "$actual_uv" in
    "uv $UV_VERSION"*) ;;
    *)
        echo "ERROR: expected uv $UV_VERSION, found: $actual_uv" >&2
        exit 1
        ;;
esac

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

compile_dev() {
    local output="$1"
    local args=(
        pip compile pyproject.toml
        --extra dev
        --universal
        --generate-hashes
        --no-header
        --output-file "$output"
    )
    if [[ "$MODE" != "--upgrade" && -f requirements-dev.lock ]]; then
        args+=(--constraint requirements-dev.lock)
    fi
    uv "${args[@]}"
}

compile_input() {
    local input="$1"
    local lock="$2"
    local output="$3"
    local args=(
        pip compile "$input"
        --python-version 3.10
        --universal
        --generate-hashes
        --no-header
        --output-file "$output"
    )
    if [[ "$MODE" != "--upgrade" && -f "$lock" ]]; then
        args+=(--constraint "$lock")
    fi
    uv "${args[@]}"
}

write_lock() {
    local destination="$1"
    local source_name="$2"
    local body="$3"
    {
        printf '# Generated by scripts/regenerate-locks.sh with uv %s.\n' "$UV_VERSION"
        printf '# Source: %s\n' "$source_name"
        printf '# Regenerate: scripts/regenerate-locks.sh --write\n'
        # Resolver provenance comments can vary when the current lock is used as
        # a constraint. Remove comments and blank lines while preserving every
        # requirement, marker, and hash that pip enforces.
        tr -d '\r' < "$body" | grep -vE '^[[:space:]]*(#|$)' || true
    } > "$destination"
}

render_all() {
    local destination="$1"
    local raw="$WORK/raw"
    mkdir -p "$destination" "$raw"

    compile_dev "$raw/requirements-dev.lock"
    write_lock "$destination/requirements-dev.lock" \
        'pyproject.toml --extra dev' "$raw/requirements-dev.lock"

    compile_input requirements-build.in requirements-build.lock \
        "$raw/requirements-build.lock"
    write_lock "$destination/requirements-build.lock" \
        requirements-build.in "$raw/requirements-build.lock"

    compile_input requirements-release.in requirements-release.lock \
        "$raw/requirements-release.lock"
    write_lock "$destination/requirements-release.lock" \
        requirements-release.in "$raw/requirements-release.lock"
}

if [[ "$MODE" == "--check" ]]; then
    generated="$WORK/generated"
    render_all "$generated"
    status=0
    for lock in requirements-dev.lock requirements-build.lock requirements-release.lock; do
        if ! cmp -s "$lock" "$generated/$lock"; then
            echo "ERROR: $lock is stale. Run scripts/regenerate-locks.sh --write." >&2
            diff -u "$lock" "$generated/$lock" || true
            status=1
        fi
    done
    exit "$status"
fi

render_all "$WORK/generated"
for lock in requirements-dev.lock requirements-build.lock requirements-release.lock; do
    cp "$WORK/generated/$lock" "$lock"
done
